# Generated by Django 3.1.3 on 2020-11-04 19:16

import biography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[(biography.models.Gender['M'], 'Male'), (biography.models.Gender['F'], 'Female'), (biography.models.Gender['T'], 'Transgender'), (biography.models.Gender['GQ'], 'Genderqueer'), (biography.models.Gender['A'], 'Agender'), (biography.models.Gender['G'], 'Genderless'), (biography.models.Gender['N'], 'Non-binary'), (biography.models.Gender['TM'], 'Trans Man'), (biography.models.Gender['TF'], 'Trans Woman'), (biography.models.Gender['TG'], 'Third Gender'), (biography.models.Gender['TS'], 'Two-Spirit'), (biography.models.Gender['BG'], 'Bigender'), (biography.models.Gender['GF'], 'Genderfluid')], max_length=5)),
                ('interested_in', models.CharField(choices=[(biography.models.Gender['M'], 'Male'), (biography.models.Gender['F'], 'Female'), (biography.models.Gender['T'], 'Transgender'), (biography.models.Gender['GQ'], 'Genderqueer'), (biography.models.Gender['A'], 'Agender'), (biography.models.Gender['G'], 'Genderless'), (biography.models.Gender['N'], 'Non-binary'), (biography.models.Gender['TM'], 'Trans Man'), (biography.models.Gender['TF'], 'Trans Woman'), (biography.models.Gender['TG'], 'Third Gender'), (biography.models.Gender['TS'], 'Two-Spirit'), (biography.models.Gender['BG'], 'Bigender'), (biography.models.Gender['GF'], 'Genderfluid')], max_length=5)),
            ],
        ),
    ]
