# Generated by Django 3.1.3 on 2020-11-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('GQ', 'Genderqueer'), ('A', 'Agender'), ('G', 'Genderless'), ('N', 'Non-binary'), ('TM', 'Trans Man'), ('TF', 'Trans Woman'), ('TG', 'Third Gender'), ('TS', 'Two-Spirit'), ('BG', 'Bigender'), ('GF', 'Genderfluid')], max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('GQ', 'Genderqueer'), ('A', 'Agender'), ('G', 'Genderless'), ('N', 'Non-binary'), ('TM', 'Trans Man'), ('TF', 'Trans Woman'), ('TG', 'Third Gender'), ('TS', 'Two-Spirit'), ('BG', 'Bigender'), ('GF', 'Genderfluid')], max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='biography.address'),
            preserve_default=False,
        ),
    ]
