# Generated by Django 3.1.3 on 2020-11-04 21:42

import biography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0006_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Captain', 'Captain'), ('Prof', 'Professor')], default='Mr', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=biography.models.user_image_path),
        ),
    ]
