# Generated by Django 3.1.3 on 2020-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0007_auto_20201104_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_shape',
            field=models.CharField(choices=[('Avg', 'Average'), ('Ath', 'Athletic / Toned'), ('Sl', 'Slender'), ('EP', 'A Few Extra Pounds'), ('C', 'Curvy'), ('H', 'Heavy Set / Stocky'), ('F', 'Full Figured / Big Beautiful')], default='Avg', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', help_text='Describe yourself.', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('GQ', 'Genderqueer'), ('A', 'Agender'), ('G', 'Genderless'), ('N', 'Non-binary'), ('TM', 'Trans Man'), ('TF', 'Trans Woman'), ('TG', 'Third Gender'), ('TS', 'Two-Spirit'), ('BG', 'Bigender'), ('GF', 'Genderfluid')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='A title to make you stand out.', max_length=200),
        ),
    ]
