# Generated by Django 3.1.3 on 2020-11-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0011_auto_20201109_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
